target("RocketMath")
    set_kind("static")
    add_files("*.cpp")
    add_options("console_log")
    add_options("memory_check")
    add_packages("eigen", {public = true})
    add_deps("RocketCore", {public = true})
target_end()
