target("RocketVulkan")
    set_kind("static")
    add_files("*.cpp")
    add_options("console_log")
    add_options("memory_check")
    add_options("render")
    add_options("profile_settings")
    add_packages("volk", {public = true})
    add_packages("glfw", {public = true})
    add_packages("glslang", {public = true})
    add_deps("RocketLog", {public = true})
    add_deps("RocketUtils", {public = true})
target_end()
