target("soft_render_util")
    set_kind("static")
    add_files("soft_render.cpp")
    add_packages("eigen", "spdlog", "glfw", "glad", {public = true})
    add_options("console_log")
    add_options("memory_check")
target_end()
