target("memory_test")
    set_kind("binary")
    add_files("memory_test.cpp")
    add_options("memory_check")
target_end()

target("glfw_test")
    set_kind("binary")
    add_files("glfw_test.cpp")
    add_packages("glfw", "glad")
target_end()

target("log_test")
    set_kind("binary")
    add_files("log_test.cpp")
    add_deps("RocketEngine")
    add_options("console_log")
    add_options("memory_check")
target_end()

target("find_root_test")
    set_kind("binary")
    add_files("find_root_test.cpp")
    add_deps("RocketEngine")
    add_options("console_log")
    add_options("memory_check")
target_end()

target("memory_pool_test")
    set_kind("binary")
    add_files("memory_pool_test.cpp")
    add_options("console_log")
    add_options("memory_check")
target_end()

target("engine_test")
    set_kind("binary")
    add_files("engine_test.cpp")
    add_deps("RocketEngine")
    add_options("console_log")
    add_options("memory_check")
target_end()
