target("sf2float")
    set_kind("binary")
    add_deps("portsf")
    add_files("sf2float.c")
target_end()

target("sfgain")
    set_kind("binary")
    add_deps("portsf")
    add_files("sfgain.c")
target_end()

target("sfnorm")
    set_kind("binary")
    add_deps("portsf")
    add_files("sfnorm.c")
target_end()

target("sfpan")
    set_kind("binary")
    add_deps("breakpoints")
    add_deps("portsf")
    add_files("sfpan.c")
target_end()
