target("sf2float")
    set_kind("binary")
    add_deps("portsf")
    add_files("sf2float.c")
target_end()

target("sfgain")
    set_kind("binary")
    add_deps("portsf")
    add_files("sfgain.c")
target_end()

target("sfnorm")
    set_kind("binary")
    add_deps("portsf")
    add_files("sfnorm.c")
target_end()

target("sfpan")
    set_kind("binary")
    add_deps("breakpoints")
    add_deps("portsf")
    add_files("sfpan.c")
target_end()

target("envx")
    set_kind("binary")
    add_deps("breakpoints")
    add_deps("portsf")
    add_files("envx.c")
target_end()

target("sfenv")
    set_kind("binary")
    add_deps("breakpoints")
    add_deps("portsf")
    add_files("sfenv.c")
target_end()

target("siggen")
    set_kind("binary")
    add_deps("breakpoints")
    add_deps("portsf")
    add_deps("wave")
    add_files("siggen.c")
target_end()

target("tabgen")
    set_kind("binary")
    add_deps("breakpoints")
    add_deps("portsf")
    add_deps("gtable")
    add_files("tabgen.c")
target_end()

target("sfpeak")
    set_kind("binary")
    add_deps("portsf")
    add_files("sfpeak.c")
target_end()

target("oscgen")
    set_kind("binary")
    add_deps("breakpoints")
    add_deps("portsf")
    add_deps("wave")
    add_files("oscgen.c")
target_end()
