target("string_match_test")
    set_kind("binary")
    add_files("string_match_test.cpp")
    add_packages("glfw", "glad", "stb")
    add_deps("RocketLog")
    add_deps("RocketUtils")
    add_options("console_log")
    add_options("memory_check")
target_end()
