target("rust_print_test")
    set_kind("binary")
    add_files("print_test.rs")
target_end()

add_requires("cargo::base64")
add_requires("cargo::cxx")

target("add_fun")
    set_kind("static")
    add_files("add_fun.rs")
    set_values("rust.cratetype", "staticlib")
    add_packages("cargo::cxx")
target_end()

target("call_rust_test")
    set_kind("binary")
    add_rules("rust.cxxbridge")
    add_files("bridge.rsx")
    add_files("call_rust_test.cc")
    add_deps("add_fun")
target_end()
