target("search_test")
    set_kind("binary")
    add_files("search_test.cpp")
target_end()

target("sort_test")
    set_kind("binary")
    add_files("sort_test.cpp")
    add_deps("RocketEngine")
    add_options("console_log")
    add_options("memory_check")
target_end()

target("quickhall_test")
    set_kind("binary")
    add_files("quickhall_test.cpp")
    add_deps("RocketEngine")
    add_options("console_log")
    add_options("memory_check")
target_end()
