name: xmake-all

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Install xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest
    
    - name: Goto WorkDir
      run: cd ${{github.workspace}}
    
    - name: Change to Release
      run: xmake f -y -m release

    - name: Build Project
      run: xmake -y

    - name: Change to Debug
      run: xmake f -y -m debug

    - name: Build Project
      run: xmake -y
