name: xmake-all

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        #os: [ubuntu-latest, macos-latest, windows-latest]
        os: [macos-latest, windows-latest]
        type: [release, debug]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest
    
    - name: Goto WorkDir
      run: cd ${{github.workspace}}

    - name: Install Dependencies (Linux)
      run: sudo apt-get install libogg-dev
      if: matrix.os == 'ubuntu-latest'
    
    - name: Change to ${{ matrix.type }}
      run: xmake f -y -m ${{ matrix.type }}

    - name: Build Project
      run: xmake -vD -y
